### ISSUE TITLE
Only finding 1 WavePlus

### ISSUE THREAD

**Issue by sokratz** [custom-components/sensor.airthings_wave#33]
Seems like i can only see 1 of my waveplus devices even though manual testing of AT's python script works from pi console.   Does this support multiples?  Wasn't sure how to format multiple MACs in the optional arguments yaml.  TIA

**Comment by jreidel** [comment]
I have the same issue.

**Comment by hschmidt** [comment]
Similar issue over here:

With this config

```
sensor:
  - platform: airthings_wave
    scan_interval: 120
    elevation: 998
    mac: 00:81:F9:XX:XX:XX
  - platform: airthings_wave
    scan_interval: 120
    elevation: 998
    mac: 04:ee:03:YY:YY:YY
```

one sensor shows up as Unavailable. When I remove a config entry for one of the sensors, the other sensor is detected and yields data.
