### ISSUE TITLE
Mac and Multiple sensors

### ISSUE THREAD

**Issue by carloslema** [custom-components/sensor.airthings_wave#58]
Hi Marty

I hope all is well, thank you for this library. I am new to Hassio, so forgive me for noob question. I have a couple of Airthings Wave Plus sensors that I want to track with home assistant using the RiPi4's built in BLE vs using the cloud.

I followed the getting started direction you have, but I must be missing something.

— Where to find the sensor's MAC ID, found the BLE's characteristics. Used bluetoothd and system_profiler on Mac's terminal, but can't find any of the sensors, even though they are connected to my phone and Airthings App — Which the sync info does not list the Mac ID.

— Once I figure how pair to the devices, how to add the card that displays the sensors data in the main display?

Any help is greatly appreciated.

Best,
\\ Carlos

**Comment by MartyTremblay** [comment]
Hi @carloslema 
Can you try what is being proposed here? https://github.com/custom-components/sensor.airthings_wave/issues/43#issue-818291641

As for the cards to display, I use the custom component https://github.com/kalkih/mini-graph-card (it's in HACS)

Here's an example for radon_1day_avg:

```
color_thresholds:
  - color: var(--primary-color)
    value: 99
  - color: var(--error-color)
    value: 100
entities:
  - entity: sensor.xx_xx_xx_xx_xx_xx_radon_1day_avg
    index: 0
font_size: 75
line_width: 8
lower_bound: 0
name: Radon 1 Day Avg.
type: custom:mini-graph-card
upper_bound: 150

```
